name: build

on:
  push:
    branches:
      - 'feature/**' 

jobs:
  build:
    runs-on: ubuntu-latest # 
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Conceder permissão de execução ao Gradle
        run: chmod +x gradlew # Garante que o script do Gradle seja executável

      - name: Executar testes e build
        run: ./gradlew test build # Roda os testes e o build da aplicação

          
  validate-image:
      runs-on: ubuntu-latest
      needs: build
      if: success()
      steps:
        - name: Checkout do código
          uses: actions/checkout@v4
        
        - name: Validar o build da imagem Docker
          run: |
            docker build . --file Dockerfile
        
  create-pr:
      runs-on: ubuntu-latest
      needs: validate-image
      if: success()
      permissions:
        contents: write 
        pull-requests: write 
  
      steps:
        - name: Checkout do código para o job de PR
          uses: actions/checkout@v4
          with:
            ref: ${{ github.ref }} 
  
        - name: Criar Pull Request
          uses: peter-evans/create-pull-request@v6
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: 'feat: Automação - build e testes OK'
            title: 'PR automático: build e testes da branch ${{ github.ref_name }}'
            body: |
              Este é um PR automático criado pela GitHub Action após um build bem-sucedido.
              Todos os testes passaram.
            base: main 
            branch: ${{ github.ref_name }}
