name: test

on:
  push:
    branches:
      - 'feature/**' 

jobs:
  build:
    runs-on: ubuntu-latest # 
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Conceder permissão de execução ao Gradle
        run: chmod +x gradlew # Garante que o script do Gradle seja executável

      - name: Executar testes e build
        run: ./gradlew test build # Roda os testes e o build da aplicação
